# Generated by Django 4.0.2 on 2022-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('goodr_id', models.TextField(default=0)),
                ('author', models.TextField()),
                ('isbn', models.TextField()),
                ('my_rating', models.TextField()),
                ('avg_rating', models.TextField()),
                ('pages', models.TextField()),
                ('date_added', models.TextField()),
                ('shelf', models.TextField()),
            ],
        ),
    ]
