# Generated by Django 4.0.2 on 2022-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_document_description_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='user_uploads/%Y-%m-%d/'),
        ),
    ]
